name: arcos_globos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # <--- ESTA LÍNEA ERA OBLIGATORIA

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png         # <--- TAMBIÉN FALTABA ESTO

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/icons/icon.png"
